<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Vaishnavi" failures="0" tests="2" name="com.TestnNG.Asseration_timeOut" time="4.036" errors="1" timestamp="2024-10-29T12:11:03 IST" skipped="0">
  <testcase classname="com.TestnNG.Asseration_timeOut" name="testcase1" time="2.015"/>
  <testcase classname="com.TestnNG.Asseration_timeOut" name="testcase2" time="2.021">
    <error message="Method com.TestnNG.Asseration_timeOut.testcase2() didn&#039;t finish within the time-out 2000" type="org.testng.internal.thread.ThreadTimeoutException">
      <![CDATA[org.testng.internal.thread.ThreadTimeoutException: Method com.TestnNG.Asseration_timeOut.testcase2() didn't finish within the time-out 2000
at java.base/java.lang.Thread.sleep0(Native Method)
at java.base/java.lang.Thread.sleep(Thread.java:509)
at com.TestnNG.Asseration_timeOut.testcase2(Asseration_timeOut.java:20)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.invokers.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:141)
at org.testng.internal.invokers.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:47)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:76)
at org.testng.internal.invokers.InvokeMethodRunnable.call(InvokeMethodRunnable.java:11)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
]]>
    </error>
  </testcase> <!-- testcase2 -->
</testsuite> <!-- com.TestnNG.Asseration_timeOut -->
